#!/bin/sh
#
# Query a property from the terminal, e.g. background color.
#
# From: http://stackoverflow.com/questions/2507337
# 2015-07-29
#
# NOTE: This does not seem to work in Apple Terminal, even though it
# identifies as 'xterm-color' ($TERM).
#
# XTerm Operating System Commands
#     "ESC ] Ps;Pt ST"
#
oldstty=$(stty -g)

# What to query?
# 11: text background
Ps=${1:-11}

stty raw -echo min 0 time 0
# stty raw -echo min 0 time 1
#printf "\033]$Ps;?\033\\"
printf "\033]11;?\007"
# xterm needs the sleep (or "time 1", but that is 1/10th second).
sleep 0.00000001
read -r answer
echo $answer | cat -e
result=${answer#*;}
stty $oldstty
# Remove escape at the end.
echo $result | sed 's/[^rgb:0-9a-f/]\+$//'
