#!/usr/bin/env python
#
# show256colors
#
# Written (old), by Steven J. DeRose.
# This work by Steven J. DeRose is licensed under a Creative Commons
# Attribution-Share Alike 3.0 Unported License. For further information on
# this license, see http://creativecommons.org/licenses/by-sa/3.0/.

#
# To do:
#     show against light *and* dark backgrounds.
#
print("ANSI terminal extended colors: ESC [38;5;Xm for X from 0 to 255.")

for c in range(0,256):
    print("\x1B[38;5;%smtest of color #%d\x1B[m" % (c, c))

